config/routes.rb
BathroomStall::Application.routes.draw do
  resources :victims do
  	resources :comments
  end
  resources :users, :only => [:index, :show, :edit, :update ]

  root :to => "home#index"

  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/auth/failure' => 'sessions#failure'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	attr_accessible :message, :name
  belongs_to :users # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :provider, :uid, :name, :email
  validates_presence_of :name
  has_many :victims

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
         user.picture = auth.info.image
      end
    end
  end


end

app/models/victim.rb
class Victim < ActiveRecord::Base
	attr_accessible :city, :facebook_url, :gender, :name, :facebook_id
	has_many :comments
	require "uri"

	@@graph = Koala::Facebook::API.new

	def self.authenticate_victim(facebook_url)
		# @graph = Koala::Facebook::API.new
		@facebook_url = facebook_url
		@victim_profile_url = URI.parse(@facebook_url)
		@facebook_profile_name_with_slash = @victim_profile_url.path
		@facebook_profile_name = @facebook_profile_name_with_slash.gsub(/\//, '')
		return @@graph.get_object(@facebook_profile_name)
	end

	def find_profile_photo
		# @graph = Koala::Facebook::API.new
		@user_id = self.facebook_id
		@profile_pic = @@graph.get_picture(@user_id, {:type => "large"})
		return @profile_pic
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :redirect_back_unless_logged_in
  def create
  	# @user_id	= Rack.find(params[:user_id]
		@comment = Comment.create(params[:comment]) do |comment|
			comment.user_id = session[:user_id]
			comment.victim_id = params[:victim_id]
      comment.good_bad = params[:good_bad]
      comment.anonymous = params[:anonymous]
      comment.name = User.find(comment[:user_id]).name
      # comment.name = User.find

			# comment.save
		end



		redirect_to :back
	end


  private

	def redirect_back_unless_logged_in
		unless session[:user_id].present?
			flash[:notice] = "Please sign in to make a comment."
			redirect_to :back
			end
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/facebook'
  end

  def create
    @auth = request.env["omniauth.auth"]
    user = User.where(:provider => @auth['provider'], 
                      :uid => @auth['uid'].to_s).first || User.create_with_omniauth(@auth)
# Reset the session after successful login, per
# 2.8 Session Fixation – Countermeasures:
# http://guides.rubyonrails.org/security.html#session-fixation-countermeasures
    reset_session
    session[:user_id] = user.id
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def index
  end

  def destroy
    reset_session
    redirect_to root_url, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

  def index
    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
    
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


  def show
    @user = User.find(params[:id])
    # @user_photo = User.user_photo()
  end

end

app/controllers/victims_controller.rb
class VictimsController < ApplicationController
  # GET /victims
  # GET /victims.json
  def index
    @victims = Victim.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @victims }
    end
  end

  # GET /victims/1
  # GET /victims/1.json
  def show
    @victim = Victim.find(params[:id])
    @comment = @victim.comments.build
    @current_user = @comment.user_id
    @comments = Comment.all.reverse
    @profile_pic = @victim.find_profile_photo
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @victim }

    end
  end

  # GET /victims/new
  # GET /victims/new.json
  def new
    @victim = Victim.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @victim }
    end
  end

  # GET /victims/1/edit
  def edit
    @victim = Victim.find(params[:id])
  end

  # POST /victims
  # POST /victims.json
  def create
    @facebook_url = params[:victim][:facebook_url]
    @victim_candidate_hash = Victim.authenticate_victim(@facebook_url)
    @victim = Victim.find_or_initialize_by_facebook_url(@facebook_url) # .update_attributes(:name => @victim_candidate_hash[:name]) 
    @victim.assign_attributes(:name => @victim_candidate_hash['name'], :gender => @victim_candidate_hash['gender'], :facebook_id => @victim_candidate_hash['id'])
    respond_to do |format|
      if @victim.persisted?
        format.html { redirect_to @victim, notice: "#{@victim.name} is already in here. Go ahead and add your comment." }
        format.json { render json: @victim, status: :created, location: @victim }
      elsif @victim.save
        format.html { redirect_to @victim, notice: "You successfully invited #{@victim.name} to the bathroom." }
        format.json { render json: @victim, status: :created, location: @victim }
      else
        format.html { render action: "new" }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /victims/1
  # PUT /victims/1.json
  def update
    @victim = Victim.find(params[:id])

    respond_to do |format|
      if @victim.update_attributes(params[:victim])
        format.html { redirect_to @victim, notice: 'Victim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @victim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /victims/1
  # DELETE /victims/1.json
  def destroy
    @victim = Victim.find(params[:id])
    @victim.destroy

    respond_to do |format|
      format.html { redirect_to victims_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def he_or_she
		@victim = Victim.find(params[:id])
			if @victim.gender == 'female'
				return 'she'
			elsif @victim.gender == 'male'
				return 'he'
			else
				return 'this person'
			end
	end

	# He is the one who went to his house. It was him.
	# She is the one who went to her house. It was her.
	# This user is the one who went to 

	def him_or_her
		@victim = Victim.find(params[:id])
			if @victim.gender == 'female'
				return 'her'
			elsif @victim.gender == 'male'
				return 'him'
			else 
				return ''
			end
	end


end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/victims_helper.rb
module VictimsHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%div.navigation
  = link_to "Bathroom Stall", root_path, :class => 'brand'
  %div.credentials
    - if user_signed_in?
      %p.nav
        Logged in as
        = link_to current_user.name, user_path(current_user.id), :class=>'user'
        %br
        = link_to "Review", victims_path, :class => 'smallbrand'
        |
        = link_to "New", new_victim_path, :class => 'smallbrand'
        |
        = link_to 'Logout', signout_path, :class => 'smallbrand'
    - else
      %p.nav
        = link_to "Read", victims_path, :class => 'smallbrand'
        |
        = link_to 'Login', signin_path, :class => 'smallbrand'
  %br
  %br
  %br
  %p.tag
    The People Reviewer

app/views/layouts/application.html.haml
!!!
%html
  %head

    %link{:rel => 'stylesheet', :type => 'text/css', :href => 'http://fonts.googleapis.com/css?family=Rock+Salt|Crafty+Girls|Shadows+Into+Light'}
    
    
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Bathroom Stall"
      %meta{:content => content_for?(:description) ? yield(:description) : "Bathroom Stall", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)


  %body{:class => "#{controller_name} #{action_name}"}
    #container
      %header
        = render 'layouts/navigation'
        = render 'layouts/messages'
      #main{:role => "main"}
        = yield
      %footer
        = render 'layouts/footer'
    / ! end of #container

app/views/users/_form.html.erb
<div class="hatch_form">
  <%= form_for(@victim) do |f| %>
    <% if @victim.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@victim.errors.count, "error") %> prohibited this flock from being saved:</h2>

        <ul>
        <% @victim.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    
    
      <form class="victim_form", action="/victim/create", method="post">
        <div class="form_div">
          <h3> Who would you like to review? </h3>
          Link to Facebook profile: <input type="text" class="input" name="victim[][handle]"> <br />
          E-mail Address: <input type="text" class="input" name="tweeters[][email]"> <br />
          Name: <input type="text" class="input" name="tweeters[][name]"> <br />

        </div>    
        
        <input type="button" name="add" class="new_tweeter" value="Add a Tweeter" />

        <div class="actions">
          <input type="submit" value="Get Flocking!", class: "flock_create" %>
        </div>

      </form>
    
    
  <% end %>
</div>

app/views/users/edit.html.haml
= form_for(@user) do |f|
  = f.label :email
  = f.text_field :email
  %br/
  = f.submit "Sign in"

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}

%p Photo: #{@user_photo}

app/views/victims/_form.html.haml
= form_for @victim do |f|
  - if @victim.errors.any?
    #error_explanation
      %h2= "#{pluralize(@victim.errors.count, "error")} prohibited this victim from being saved:"
      %ul
        - @victim.errors.full_messages.each do |msg|
          %li= msg

  / .field
  /   = f.label :name
  /   = f.text_field :name
  .field
    = f.label :facebook_url
    = f.text_field :facebook_url
  / .field
  /   = f.label :gender
  /   = f.text_field :gender
  / .field
  /   = f.label :city
  /   = f.text_field :city
  .actions
    = f.submit 'Save'

app/views/victims/_formnewvictim.html.erb
<div class="victim_form">
  <%= form_for(@victim) do |f| %>
    <% if @victim.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@victim.errors.count, "error") %> prohibited this flock from being saved:</h2>

        <ul>
        <% @victim.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    
    
      <form class="victim_form", action="/victim/create", method="post">
        <div class="form_div">
          <h3> Who are you writing about? </h3> <br />
          Facebook URL: <%= f.text_field :facebook_url, :autofocus => true %> <br />
         <!--  Name: <%= f.text_field :name, :autofocus => true %> <br />
          Gender: <%= f.text_field :gender, :autofocus => true %> <br />
          City: <%= f.text_field :city, :autofocus => true %> <br /> -->
        </div>


        <div class="actions">
          <input type="submit" value="Generate a Stall", class: "victim_create" %>
        </div>

      </form>
    
    
  <% end %>
</div>

app/views/victims/_formreview.html.erb
<!-- <div class="comment_form">
  <%= form_for[@victim, @comment] do |f| %>
    <% if @victim.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@victim.errors.count, "error") %> prohibited this scrawl from being saved:</h2>

        <ul>
        <% @victim.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    
    
      <form class="victim_form", action="/victim/create", method="post">
        <div class="form_div">
          <h3> Add a Scrawl </h3>
          Love or hate? <input type="radio" class="input" name="victim[][good_or_bad]" value="Love"> 
          <input type="radio" class="input" name="victim[][good_or_bad]" value="Hate"> <br />
          Write your review: <input type="text" class="input" name="victim[][name]"> <br />
          gender: <input type="text" class="input" name="victim[][review]"> <br />
          
        </div>


        <div class="actions">
          <input type="submit" value="Save", class: "victim_create" %>
        </div>

      </form>
    
    
  <% end %>
</div> -->

app/views/victims/edit.html.haml
%h1 Editing victim

= render 'form'

= link_to 'Show', @victim
\|
= link_to 'Back', victims_path

app/views/victims/index.html.haml
.container
  
  .six.columns
    %h1.title Browse People
  .six.columns.offset-by-four
    %h3.find_your_person 
      =button_to "Add a Person", new_victim_path, :method => "get", :class => 'here'
  .sixteen.columns
    - @victims.each do |victim|
      .holder
        - @photo = victim.find_profile_photo
        %div.three.columns
          = link_to victim do
            .image= image_tag(@photo, :height => '100', :width => 'auto')
            .listname=victim.name
            

      / %td= link_to 'Edit', edit_victim_path(victim)
      / %td= link_to 'Destroy', victim, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/victims/new.html.haml
.container
  .twelve.columns.add-bottom
    %h1.title
      Hi!
    %h3
      To get started, copy the facebook url of the person you want to write about.
    %br
    = render 'form'

app/views/victims/show.html.haml
.container.victim_width

  .five.columns.add-bottom
    %center  
      .victim_card
        %center
          .victim_card_container
            %h1.victim_name
              = @victim.name
            .img_tag
              = image_tag(@profile_pic, :class => "victim")
            .edit_options
              = link_to 'Edit', edit_victim_path(@victim)
              \|
              = link_to 'Back', victims_path

          
  .eleven.columns.add-bottom
    .scrawl_container
      %center
        %h2.scrawl Stall Scrawl




      %h3 Add A Comment
      = form_for [@victim, @comment] do |f|
        - if @comment.errors.any?
          #error_explanation
            %h2= pluralize(@comment.errors.count, "error") + 'prohibited this comment from being saved.'

          %ul
            = @victim.errors.full_messages.each do |msg|
              %li= msg


        %div.whatthink
          = f.text_area :message, :placeholder => "What do you think of #{@victim.name}?", :class => "text_area"

        .good_or_bad
          %h5 #{@victim.name} gets ... 
          %input{:name => "good_bad", :type => "radio", :value => "Thumbs up!"} 
          Thumbs up!
          %br                     
          %input{:name => "good_bad", :type => "radio", :value => "Meh..."}  
          Meh...
        .actions= f.submit "Save Review"


        .review_container
          .review_title
            %center
              %h3.review_header Reviews for #{@victim.name}
          .all_reviews
            - @comments.each do |comment|
              - if comment.victim_id == @victim.id
                .each_review
                  .name.twelve.columns
                    = comment.good_bad 
                    .goodbad.two.columns
                      = comment.name 
                    .reviewtext.offset-by-two.ten.columns
                      = comment.message
                %hr.review_line

        / .anonymous_or_not
        /   %h5 Anonymity Settings
        /   %input{:name => "anonymous", :type => "radio", :value => current_user.name}
        /   <strong><em>Post my name</em></strong> for #{@victim.name} and everyone else to see.          
        /   %br/                      
        /   %input{:name => "anonymous", :type => "radio", :value => "Anonymous"}  
        /   Keep me <strong><em>anonymous</em></strong>.

         